// /* Core */
// import { createSlice } from "@reduxjs/toolkit";
// import { initialState } from "./state";
// import { getNewsAsync, getNewsByIdAsync } from "./thunks";
// import {
//   getNewsFulfilledCaseReducer,
//   getNewsPendingCaseReducer,
//   getNewsByIdFulfilledCaseReducer,
//   getNewsByIdPendingCaseReducer,
//   getNewsByIdRejectedCaseReducer,
//   addNewsReducer,
// } from "./reducers";

// export const seriesSlice = createSlice({
//   name: "series",
//   initialState,
//   // The `reducers` field lets us define reducers and generate associated actions
//   reducers: {
//     addSerie: addNewsReducer,
//   },
//   // The `extraReducers` field lets the slice handle actions defined elsewhere,
//   // including actions generated by createAsyncThunk or in other slices.
//   extraReducers: (builder) => {
//     builder
//       // GetSeries
//       .addCase(getNewsAsync.pending, getNewsPendingCaseReducer)
//       .addCase(getNewsAsync.fulfilled, getNewsFulfilledCaseReducer)
//       // GetSerieById
//       .addCase(getNewsByIdAsync.pending, getNewsByIdPendingCaseReducer)
//       .addCase(getNewsByIdAsync.fulfilled, getNewsByIdFulfilledCaseReducer)
//       .addCase(getNewsByIdAsync.rejected, getNewsByIdRejectedCaseReducer);
//   },
// });
