/* Core */
import { createSlice } from "@reduxjs/toolkit";
import { initialState } from "./state";
import { getActorAsync, getActorByIdAsync } from "./thunks";
import {
  getActorFulfilledCaseReducer,
  getActorPendingCaseReducer,
  getActorByIdFulfilledCaseReducer,
  getActorByIdPendingCaseReducer,
  getActorByIdRejectedCaseReducer,
  addActorReducer,
} from "./reducers";

export const actorSlice = createSlice({
  name: "actor",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    // addActor: addActorReducer,
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder;
  },
});

const actions = actorSlice.actions;

export { actions };
